name: Build and Push

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - context: ./arm/telegraf
            tag: telegraf-arm-v2
          - context: ./mips/telegraf
            tag: telegraf-mips-v2
          - context: ./arm/unfsd
            tag: unfsd-v2
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -    
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ github.repository }}:${{ matrix.tag }}